Upgrade keycloak-on-aws to support quarkus versions
aws-samples/keycloak-on-aws pull request #400
Opened 2023-10-18 03:01 UTC by hpp222

Fixed #361 ,  #385 , #388 ,  #398 

* Upgrade keycloak to 22.0.4
* Upgrade aws-cdk-lib to 2.100.0
* Upgrade cdk Keycloak to 2.9.0
* Upgrade Aurora Serverless for MySQL to v2  
* Support customizable task cpu and memory settings
* Update implementation guide
* Tested in ap-northeast-1

2023-10-19 13:08 UTC, wchaws requested changes

2023-10-19 13:08 UTC, wchaws commented on docs/zh/implementation-guide/revisions.md
> +| 2023年10月 | 发布版本2.1.6 <br> 1. 升级 Keycloak 版本至 22.0.4 <br> 2. 升级 aws-cdk 版本至 2.100.0 <br> 3. 升级 cdk-keycloak 版本至 2.9.0 |
Can you please create a new line?

2023-10-19 13:11 UTC, hpp222 commented on docs/zh/implementation-guide/revisions.md
> +| 2023年10月 | 发布版本2.1.6 <br> 1. 升级 Keycloak 版本至 22.0.4 <br> 2. 升级 aws-cdk 版本至 2.100.0 <br> 3. 升级 cdk-keycloak 版本至 2.9.0 |
👌

2023-10-26 08:13 UTC, wchaws approved these changes

2023-10-26 08:15 UTC, merged